# HP / MP variables
MIN_MAX_HP = 1
MIN_MAX_MP = 0

# speed variables
MIN_SPEED_STEP = -3
MAX_SPEED_STEP = 3
BASE_TURN_COST = 100
SPEED_STEP_DIVISOR = 3
SPEED_MULTIPLIER_BASE = 2

# reward variables
LUCK_BASE = 2
LUCK_DIVISOR = 100
MIN_REWARD_RATE = 0.0
MAX_REWARD_RATE = 100.0
MIN_DROP_BONUS = -80.0
MAX_DROP_BONUS = 200.0
