# HP / MP variables
MIN_MAX_HP = 1
MIN_MAX_MP = 0

# attack - defence variables
DEFENSE_BASE_VALUE = 50
EXCESS_PENETRATION_HIGH_EFFICIENCY_LIMIT = 20
EXCESS_PENETRATION_HIGH_EFFICIENCY_DAMAGE_RATE = 0.015
EXCESS_PENETRATION_LOW_EFFICIENCY_DAMAGE_RATE = 0.005

# accuracy - evasion variables
BASE_HIT_RATE = 60.0
MIN_HIT_RATE = 20.0
MAX_HIT_RATE = 100.0
HIT_RATE_HIGH_EFFICIENCY_LIMIT = 20
HIT_RATE_HIGH_EFFICIENCY_STEP = 4.0
HIT_RATE_LOW_EFFICIENCY_STEP = 2.0

# speed variables
MIN_SPEED_STEP = -3
MAX_SPEED_STEP = 3
BASE_TURN_COST = 100
SPEED_STEP_DIVISOR = 3
SPEED_MULTIPLIER_BASE = 2

# critical variables
MIN_CRITICAL_RATE = -100.0
MAX_CRITICAL_RATE = 100.0
BASE_CRITICAL_DAMAGE = 75.0
MIN_CRITICAL_DAMAGE = 0.0
UNDER_CRITICAL_DAMAGE_MODIFIER = 0.25

# damage increase variables
MIN_DAMAGE_INCREASE = -80.0

# incoming damage variables
MAX_INCOMING_DAMAGE_REDUCTION = 80.0

# oversaturation variables
OVERSATURATION_DAMAGE_RATE = 0.05

# random damage variables
MIN_RANDOM_DAMAGE_MODIFIER = 0.9
MAX_RANDOM_DAMAGE_MODIFIER = 1.1

# reward variables
LUCK_BASE = 2
LUCK_DIVISOR = 100
MIN_REWARD_RATE = 0.0
MAX_REWARD_RATE = 100.0
MIN_DROP_BONUS = -80.0
MAX_DROP_BONUS = 200.0
